### ISSUE TITLE
Circuit boards are not up to date

### ISSUE THREAD

**Issue by SerGreen** [KirkMcDonald/satisfactory-calculator#23]
The amount of circuit boards produced and required for other recipes was doubled in 0.2.1 patch.  

For example: calculator says that i would need 6 Assemblers to produce 45 circuit boards/min, but in fact it would take only 3. Similarly, 5 A.I. limiters/min require 10 circuit boards/min, but the calculator says it's only 5/min.

**Comment by KirkMcDonald** [comment]
Fixed in 391c5c28292d77cb463f1d6f6eb4cfb975509dc9 and 7100d7983f5d629e123226ce576e07f4a14876a8.
