### ISSUE TITLE
Support for Update 3

### ISSUE THREAD

**Issue by JasonGCodes** [KirkMcDonald/satisfactory-calculator#28]
Do you intend to update this calculator to include the changes made in [Update 3](https://satisfactorynews.com/satisfactory-patch-notes-update-3/)?

**Comment by DW-TheWeasel** [comment]
@KirkMcDonald This is the best calculator available.  I hope you will update it to work with Update 3

**Comment by skribs** [comment]
I hope this does get updated.  This is the only calculator I'm able to follow, and I keep missing a variable when I try to do the spreadsheets myself.

**Comment by TBK** [comment]
There are people working on supporting upd 3 - https://github.com/KirkMcDonald/satisfactory-calculator/network

Join the effort and it will go faster.

**Comment by KirkMcDonald** [comment]
I have only just recently started playing with Update 3, and I've been thinking about what is required for its support in this calculator.

The greatest change in the game, from the perspective of this calculator, is the addition of recipes which produce multiple items, and the addition of recipe cycles. This means that the current naive graph traversal is no longer an adequate solution, and I will need to employ something more sophisticated.

As it happens, I have already solved a similar problem in my Factorio calculator (which has suffered a similar degree of neglect, but that is a problem for another project). Supporting Update 3 will most likely involve porting some of the linear programming code from that project, as well as the fork I made of d3-sankey that is capable of rendering cycles.

This will mean a substantial change to the internal workings of the calculator, and I am still considering how best to do it. One problem that I'm now mulling over is that Satisfactory now offers a truly dizzying array of alternate recipes, and the current UI of manually selecting the alt recipe for each item may no longer be ideal.

**Comment by skribs** [comment]
I'll be patient.  I just wanted to know this was still an active project.  A lot of game tools get abandoned when the developer leaves a game, which I now know is not the case for this tool.

Thanks!

**Comment by KirkMcDonald** [comment]
I've been investigating the new recipe graph, and made a visualization of it.

![graph](https://user-images.githubusercontent.com/396768/78319188-7bcfbc80-751b-11ea-9287-c5b36fd95e94.png)

That's a big, incomprehensible tangle, but the subset of just the recipes that go in the refinery is a little more useful:

![oilgraph](https://user-images.githubusercontent.com/396768/78319252-9dc93f00-751b-11ea-8293-90b1fac2405d.png)

**Comment by KirkMcDonald** [comment]
The calculator has been updated to 1.0.
