### ISSUE TITLE
DSP Incorrect price (And craft time?) for alternative crystal silicon

### ISSUE THREAD

**Issue by sporefreak** [KirkMcDonald/satisfactory-calculator#38]
https://dsp-wiki.com/Crystal_Silicon

Calculator seems to indicate it makes 1 per craft, and takes 4 seconds to craft the alternative recipe, telling me I need to have 96 crafting machines to get 24 crystal silicon a second.

**Comment by KirkMcDonald** [comment]
This is the issue tracker for my Satisfactory calculator. If someone forked it and put DSP data in it, then unfortunately I cannot help with that.

**Comment by JasperGems** [comment]
you dont understand me nor do i understand you
